"""도구 레지스트리와 질의 세트.

정답 도구 20개 + 방해 도구 70개.
방해 도구에는 정답과 의미가 겹치는 것들을 일부러 섞었다.
문헌이 지목하는 붕괴 원인이 (1) 긴 컨텍스트, (2) 의미가 겹치는 설명 간 혼동이기 때문이다.
"""

# (name, description) - 질의 20종의 정답이 되는 도구들
TARGETS = [
    ("send_email",          "Send an email message to one or more recipients."),
    ("create_calendar_event", "Create a new event on the user's calendar with a time and title."),
    ("search_files",        "Search for files on disk by filename pattern."),
    ("run_sql_query",       "Execute a read-only SQL query against the analytics database."),
    ("resize_image",        "Resize an image file to the given width and height."),
    ("translate_text",      "Translate a piece of text from one language to another."),
    ("get_stock_price",     "Get the current market price of a stock ticker."),
    ("create_github_issue", "Open a new issue in a GitHub repository."),
    ("book_flight",         "Book a flight ticket for a given route and date."),
    ("convert_currency",    "Convert an amount of money from one currency to another."),
    ("summarize_document",  "Produce a short summary of a long document."),
    ("deploy_service",      "Deploy a service to the production cluster."),
    ("cancel_subscription", "Cancel the user's paid subscription plan."),
    ("transcribe_audio",    "Convert spoken audio into written text."),
    ("check_disk_usage",    "Report how much disk space is used and free on a host."),
    ("create_pull_request", "Open a pull request from one branch to another."),
    ("send_slack_message",  "Post a message to a Slack channel."),
    ("rotate_api_key",      "Generate a new API key and revoke the previous one."),
    ("export_report_pdf",   "Export a saved report as a PDF file."),
    ("scale_replicas",      "Change the number of running replicas for a deployment."),
]

# 질의 -> 정답 도구
QUERIES = [
    ("Let my manager know by email that the report is ready.",            "send_email"),
    ("Put a 30 minute sync with the design team on Thursday at 2pm.",     "create_calendar_event"),
    ("Find every file on this machine whose name ends with .csv.",        "search_files"),
    ("How many orders were placed last month? Check the warehouse.",      "run_sql_query"),
    ("This photo is 4000px wide, make it 800px wide.",                    "resize_image"),
    ("Turn this Korean paragraph into English.",                          "translate_text"),
    ("What is Apple trading at right now?",                               "get_stock_price"),
    ("File a bug report on the backend repository about the login crash.", "create_github_issue"),
    ("I need to fly to Tokyo on the 3rd of next month.",                  "book_flight"),
    ("How much is 250 US dollars in Korean won?",                         "convert_currency"),
    ("Give me the gist of this 40 page contract.",                        "summarize_document"),
    ("Ship the current build to production.",                             "deploy_service"),
    ("Stop billing me, I don't want the plan anymore.",                   "cancel_subscription"),
    ("Here is a recording of the meeting, I want it in text.",            "transcribe_audio"),
    ("Is the server running out of storage?",                             "check_disk_usage"),
    ("I finished the feature branch, get it reviewed and merged.",        "create_pull_request"),
    ("Tell the team in the #general channel that the incident is over.",  "send_slack_message"),
    ("Our token may have leaked, issue a fresh one and kill the old.",    "rotate_api_key"),
    ("I want this dashboard as a PDF I can attach.",                      "export_report_pdf"),
    ("Traffic is spiking, run more instances of the web deployment.",     "scale_replicas"),
]

# 방해 도구. 앞쪽 일부는 정답과 의미가 겹치도록 일부러 비슷하게 썼다.
DISTRACTORS = [
    ("send_sms",             "Send a short text message to a phone number."),
    ("send_push_notification", "Send a push notification to the user's mobile device."),
    ("draft_email",          "Create an email draft without sending it."),
    ("reply_to_email",       "Reply to an existing email thread."),
    ("create_reminder",      "Create a personal reminder at a given time."),
    ("update_calendar_event", "Change the time or title of an existing calendar event."),
    ("list_calendar_events", "List events on the calendar for a date range."),
    ("find_free_slot",       "Find a time slot where all attendees are available."),
    ("grep_file_contents",   "Search inside files for a text pattern."),
    ("list_directory",       "List the files in a directory."),
    ("move_file",            "Move or rename a file on disk."),
    ("delete_file",          "Delete a file from disk."),
    ("run_python_snippet",   "Execute a short Python snippet and return the output."),
    ("describe_table",       "Show the column names and types of a database table."),
    ("export_query_csv",     "Run a query and save the result as a CSV file."),
    ("crop_image",           "Crop an image to a given rectangle."),
    ("compress_image",       "Reduce the file size of an image."),
    ("convert_image_format", "Convert an image between formats such as PNG and JPEG."),
    ("detect_language",      "Detect which language a piece of text is written in."),
    ("proofread_text",       "Fix grammar and spelling in a piece of text."),
    ("rewrite_text",         "Rewrite text in a different tone or style."),
    ("get_crypto_price",     "Get the current price of a cryptocurrency."),
    ("get_exchange_rate",    "Look up the exchange rate between two currencies."),
    ("get_weather",          "Get the current weather for a location."),
    ("create_jira_ticket",   "Create a ticket in the Jira project tracker."),
    ("comment_on_issue",     "Add a comment to an existing issue."),
    ("close_issue",          "Close an issue in a repository."),
    ("list_repositories",    "List repositories the user has access to."),
    ("merge_pull_request",   "Merge an open pull request."),
    ("review_pull_request",  "Leave a review on an open pull request."),
    ("create_branch",        "Create a new git branch."),
    ("book_hotel",           "Reserve a hotel room for a date range."),
    ("book_train",           "Book a train ticket between two stations."),
    ("rent_car",             "Reserve a rental car."),
    ("cancel_booking",       "Cancel an existing travel booking."),
    ("upgrade_subscription", "Move the user to a higher paid plan."),
    ("get_invoice",          "Fetch a past invoice for the account."),
    ("update_payment_method", "Change the card used for billing."),
    ("summarize_thread",     "Summarize a long chat or email thread."),
    ("extract_entities",     "Extract named entities from a piece of text."),
    ("classify_document",    "Assign a category label to a document."),
    ("ocr_image",            "Extract text from an image of a document."),
    ("synthesize_speech",    "Turn written text into spoken audio."),
    ("diarize_audio",        "Label which speaker said what in an audio recording."),
    ("rollback_deployment",  "Roll back a deployment to the previous version."),
    ("restart_service",      "Restart a running service."),
    ("get_service_logs",     "Fetch recent logs for a service."),
    ("get_cpu_usage",        "Report CPU utilization for a host."),
    ("get_memory_usage",     "Report memory utilization for a host."),
    ("list_running_pods",    "List the pods currently running in the cluster."),
    ("set_resource_limits",  "Set CPU and memory limits for a deployment."),
    ("create_alert_rule",    "Create a monitoring alert rule."),
    ("silence_alert",        "Temporarily silence a firing alert."),
    ("acknowledge_incident", "Acknowledge an ongoing incident."),
    ("create_api_key",       "Create a new API key."),
    ("revoke_api_key",       "Revoke an existing API key."),
    ("list_api_keys",        "List the API keys on the account."),
    ("reset_password",       "Reset a user's password."),
    ("grant_permission",     "Grant a permission to a user or role."),
    ("export_report_csv",    "Export a saved report as a CSV file."),
    ("schedule_report",      "Schedule a report to be generated periodically."),
    ("share_dashboard",      "Share a dashboard with another user."),
    ("create_dashboard",     "Create a new dashboard."),
    ("upload_file",          "Upload a file to cloud storage."),
    ("download_file",        "Download a file from cloud storage."),
    ("generate_signed_url",  "Create a temporary signed download URL."),
    ("send_teams_message",   "Post a message to a Microsoft Teams channel."),
    ("create_channel",       "Create a new chat channel."),
    ("invite_user",          "Invite a user to the workspace."),
    ("archive_channel",      "Archive a chat channel."),
]

assert len({n for n, _ in TARGETS}) == len(TARGETS) == 20
assert len({n for n, _ in DISTRACTORS}) == len(DISTRACTORS) >= 70
assert {q[1] for q in QUERIES} == {n for n, _ in TARGETS}
_names = {n for n, _ in TARGETS} | {n for n, _ in DISTRACTORS}
assert len(_names) == len(TARGETS) + len(DISTRACTORS), "이름 중복"
